export const ALL_COUNTRIES = [
  { name: "Afganistán", code: "AFG" },
  { name: "Albania", code: "ALB" },
  { name: "Alemania", code: "DEU" },
  { name: "Andorra", code: "AND" },
  { name: "Angola", code: "AGO" },
  { name: "Antigua y Barbuda", code: "ATG" },
  { name: "Arabia Saudita", code: "SAU" },
  { name: "Argelia", code: "DZA" },
  { name: "Argentina", code: "ARG" },
  { name: "Armenia", code: "ARM" },
  { name: "Australia", code: "AUS" },
  { name: "Austria", code: "AUT" },
  { name: "Azerbaiyán", code: "AZE" },
  { name: "Bahamas", code: "BHS" },
  { name: "Bangladés", code: "BGD" },
  { name: "Barbados", code: "BRB" },
  { name: "Baréin", code: "BHR" },
  { name: "Bélgica", code: "BEL" },
  { name: "Belice", code: "BLZ" },
  { name: "Benín", code: "BEN" },
  { name: "Bielorrusia", code: "BLR" },
  { name: "Birmania", code: "MMR" },
  { name: "Bolivia", code: "BOL" },
  { name: "Bosnia y Herzegovina", code: "BIH" },
  { name: "Botsuana", code: "BWA" },
  { name: "Brasil", code: "BRA" },
  { name: "Brunéi", code: "BRN" },
  { name: "Bulgaria", code: "BGR" },
  { name: "Burkina Faso", code: "BFA" },
  { name: "Burundi", code: "BDI" },
  { name: "Bután", code: "BTN" },
  { name: "Cabo Verde", code: "CPV" },
  { name: "Camboya", code: "KHM" },
  { name: "Camerún", code: "CMR" },
  { name: "Canadá", code: "CAN" },
  { name: "Catar", code: "QAT" },
  { name: "Chad", code: "TCD" },
  { name: "Chile", code: "CHL" },
  { name: "China", code: "CHN" },
  { name: "Chipre", code: "CYP" },
  { name: "Ciudad del Vaticano", code: "VAT" },
  { name: "Colombia", code: "COL" },
  { name: "Comoras", code: "COM" },
  { name: "Corea del Norte", code: "PRK" },
  { name: "Corea del Sur", code: "KOR" },
  { name: "Costa de Marfil", code: "CIV" },
  { name: "Costa Rica", code: "CRI" },
  { name: "Croacia", code: "HRV" },
  { name: "Cuba", code: "CUB" },
  { name: "Dinamarca", code: "DNK" },
  { name: "Dominica", code: "DMA" },
  { name: "Ecuador", code: "ECU" },
  { name: "Egipto", code: "EGY" },
  { name: "El Salvador", code: "SLV" },
  { name: "Emiratos Árabes Unidos", code: "ARE" },
  { name: "Eritrea", code: "ERI" },
  { name: "Eslovaquia", code: "SVK" },
  { name: "Eslovenia", code: "SVN" },
  { name: "España", code: "ESP" },
  { name: "Estados Unidos", code: "USA" },
  { name: "Estonia", code: "EST" },
  { name: "Etiopía", code: "ETH" },
  { name: "Filipinas", code: "PHL" },
  { name: "Finlandia", code: "FIN" },
  { name: "Fiyi", code: "FJI" },
  { name: "Francia", code: "FRA" },
  { name: "Gabón", code: "GAB" },
  { name: "Gambia", code: "GMB" },
  { name: "Georgia", code: "GEO" },
  { name: "Ghana", code: "GHA" },
  { name: "Granada", code: "GRD" },
  { name: "Grecia", code: "GRC" },
  { name: "Guatemala", code: "GTM" },
  { name: "Guyana", code: "GUY" },
  { name: "Guinea", code: "GIN" },
  { name: "Guinea-Bisáu", code: "GNB" },
  { name: "Guinea Ecuatorial", code: "GNQ" },
  { name: "Haití", code: "HTI" },
  { name: "Honduras", code: "HND" },
  { name: "Hungría", code: "HUN" },
  { name: "India", code: "IND" },
  { name: "Indonesia", code: "IDN" },
  { name: "Irak", code: "IRQ" },
  { name: "Irán", code: "IRN" },
  { name: "Irlanda", code: "IRL" },
  { name: "Islandia", code: "ISL" },
  { name: "Islas Marshall", code: "MHL" },
  { name: "Islas Salomón", code: "SLB" },
  { name: "Israel", code: "ISR" },
  { name: "Italia", code: "ITA" },
  { name: "Jamaica", code: "JAM" },
  { name: "Japón", code: "JPN" },
  { name: "Jordania", code: "JOR" },
  { name: "Kazajistán", code: "KAZ" },
  { name: "Kenia", code: "KEN" },
  { name: "Kirguistán", code: "KGZ" },
  { name: "Kiribati", code: "KIR" },
  { name: "Kuwait", code: "KWT" },
  { name: "Laos", code: "LAO" },
  { name: "Lesoto", code: "LSO" },
  { name: "Letonia", code: "LVA" },
  { name: "Líbano", code: "LBN" },
  { name: "Liberia", code: "LBR" },
  { name: "Libia", code: "LBY" },
  { name: "Liechtenstein", code: "LIE" },
  { name: "Lituania", code: "LTU" },
  { name: "Luxemburgo", code: "LUX" },
  { name: "Macedonia del Norte", code: "MKD" },
  { name: "Madagascar", code: "MDG" },
  { name: "Malasia", code: "MYS" },
  { name: "Malaui", code: "MWI" },
  { name: "Maldivas", code: "MDV" },
  { name: "Malí", code: "MLI" },
  { name: "Malta", code: "MLT" },
  { name: "Marruecos", code: "MAR" },
  { name: "Mauricio", code: "MUS" },
  { name: "Mauritania", code: "MRT" },
  { name: "México", code: "MEX" },
  { name: "Micronesia", code: "FSM" },
  { name: "Moldavia", code: "MDA" },
  { name: "Mónaco", code: "MCO" },
  { name: "Mongolia", code: "MNG" },
  { name: "Montenegro", code: "MNE" },
  { name: "Mozambique", code: "MOZ" },
  { name: "Namibia", code: "NAM" },
  { name: "Nauru", code: "NRU" },
  { name: "Nepal", code: "NPL" },
  { name: "Nicaragua", code: "NIC" },
  { name: "Níger", code: "NER" },
  { name: "Nigeria", code: "NGA" },
  { name: "Noruega", code: "NOR" },
  { name: "Nueva Zelanda", code: "NZL" },
  { name: "Omán", code: "OMN" },
  { name: "Países Bajos", code: "NLD" },
  { name: "Pakistán", code: "PAK" },
  { name: "Palaos", code: "PLW" },
  { name: "Palestina", code: "PSE" },
  { name: "Panamá", code: "PAN" },
  { name: "Papúa Nueva Guinea", code: "PNG" },
  { name: "Paraguay", code: "PRY" },
  { name: "Perú", code: "PER" },
  { name: "Polonia", code: "POL" },
  { name: "Portugal", code: "PRT" },
  { name: "Reino Unido", code: "GBR" },
  { name: "República Centroafricana", code: "CAF" },
  { name: "República Checa", code: "CZE" },
  { name: "República del Congo", code: "COG" },
  { name: "República Democrática del Congo", code: "COD" },
  { name: "República Dominicana", code: "DOM" },
  { name: "Ruanda", code: "RWA" },
  { name: "Rumania", code: "ROU" },
  { name: "Rusia", code: "RUS" },
  { name: "Samoa", code: "WSM" },
  { name: "San Cristóbal y Nieves", code: "KNA" },
  { name: "San Marino", code: "SMR" },
  { name: "San Vicente y las Granadinas", code: "VCT" },
  { name: "Santa Lucía", code: "LCA" },
  { name: "Santo Tomé y Príncipe", code: "STP" },
  { name: "Senegal", code: "SEN" },
  { name: "Serbia", code: "SRB" },
  { name: "Seychelles", code: "SYC" },
  { name: "Sierra Leona", code: "SLE" },
  { name: "Singapur", code: "SGP" },
  { name: "Siria", code: "SYR" },
  { name: "Somalia", code: "SOM" },
  { name: "Sri Lanka", code: "LKA" },
  { name: "Suazilandia", code: "SWZ" },
  { name: "Sudáfrica", code: "ZAF" },
  { name: "Sudán", code: "SDN" },
  { name: "Sudán del Sur", code: "SSD" },
  { name: "Suecia", code: "SWE" },
  { name: "Suiza", code: "CHE" },
  { name: "Surinam", code: "SUR" },
  { name: "Tailandia", code: "THA" },
  { name: "Taiwán", code: "TWN" },
  { name: "Tanzania", code: "TZA" },
  { name: "Tayikistán", code: "TJK" },
  { name: "Timor Oriental", code: "TLS" },
  { name: "Togo", code: "TGO" },
  { name: "Tonga", code: "TON" },
  { name: "Trinidad y Tobago", code: "TTO" },
  { name: "Túnez", code: "TUN" },
  { name: "Turkmenistán", code: "TKM" },
  { name: "Turquía", code: "TUR" },
  { name: "Tuvalu", code: "TUV" },
  { name: "Ucrania", code: "UKR" },
  { name: "Uganda", code: "UGA" },
  { name: "Uruguay", code: "URY" },
  { name: "Uzbekistán", code: "UZB" },
  { name: "Vanuatu", code: "VUT" },
  { name: "Venezuela", code: "VEN" },
  { name: "Vietnam", code: "VNM" },
  { name: "Yemen", code: "YEM" },
  { name: "Yibuti", code: "DJI" },
  { name: "Zambia", code: "ZMB" },
  { name: "Zimbabue", code: "ZWE" },
];
